### ISSUE TITLE
NPM package 1.5.0-alpha.9 is broken

### ISSUE THREAD

**Issue by EndarValuk** [dalestone/angular2-gantt#22]
I have issues when trying to use npm package 1.5.0-alpha.9.
I got following:
`
Module not found: Error: Can't resolve '
        .grid_row {
            box-sizing: border-box;
            border-bottom: 1px solid #e0e0e0;
            background-color: #fff;
            position: relative;
            -webkit-user-select: none;
            cursor:pointer;
            height:25px;
            line-height:25px;
            font-size:16px;
        }
        .grid_row:hover {
            background-color: whitesmoke;
        }
   in C:\Users\..\node_modules\ng2-gantt\activity
 @ ./~/ng2-gantt/activity/gantt-activity.component.ts 348:21-460
 @ ./~/ng2-gantt/activity/gantt-activity.module.ts
 @ ./~/ng2-gantt/gantt.module.ts
 @ ./~/ng2-gantt/index.ts
`
So further i found,  in components definition there inline styles stored in 'styleUrls' properties, but mus be in 'styles' property

**Comment by dalestone** [comment]
Try version ng2-gantt@1.9.0-alpha.9 this issue should be resolved.

**Comment by EndarValuk** [comment]
@dalestone updated package to 1.9.0-alpha.9 - still the same.

**Comment by dalestone** [comment]
OK I just encountered this on another machine, looks like you said styleUrls needs to be changed to styles. I will fix this in next update
